tasks:
  - name: Install
    init: >
      pnpm install &&
      gp sync-done install
  - name: TypeScript compiler
    init: gp sync-await install
    command: pnpm start
  - name: Editor server
    init: gp sync-await install # wait for the above 'install' to finish
    command: pnpm editor-remote
ports:
  - port: 1959
    onOpen: open-preview